import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";

const targetUrl = process.env.QA_TARGET_URL ?? "http://127.0.0.1:4173";
const artifactsDir = "artifacts/qa";
const fixturePath = `${artifactsDir}/video-locale-fixture.webm`;

await mkdir(artifactsDir, { recursive: true });
const browser = await chromium.launch({ headless: true });

// The fixture is generated by Chromium itself, so this QA does not depend on
// ffmpeg being installed on the developer machine or CI runner.
const fixturePage = await browser.newPage();
await fixturePage.setContent("<canvas id='c' width='640' height='360'></canvas>");
const videoBytes = await fixturePage.evaluate(async () => {
  const canvas = document.querySelector("#c");
  const context = canvas.getContext("2d");
  const stream = canvas.captureStream(12);
  const mimeType = ["video/webm;codecs=vp8", "video/webm"].find((type) =>
    MediaRecorder.isTypeSupported(type),
  );
  if (!mimeType) throw new Error("MediaRecorder WebM non supportato");
  const chunks = [];
  const recorder = new MediaRecorder(stream, { mimeType });
  recorder.ondataavailable = (event) => event.data.size && chunks.push(event.data);
  const stopped = new Promise((resolve) => {
    recorder.onstop = resolve;
  });
  recorder.start(250);
  const startedAt = performance.now();
  await new Promise((resolve) => {
    const draw = (now) => {
      const seconds = (now - startedAt) / 1000;
      context.fillStyle = seconds % 2 < 1 ? "#b51f2e" : "#15191f";
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.fillStyle = "white";
      context.font = "bold 46px sans-serif";
      context.fillText("CourtLab QA", 170, 160);
      context.font = "32px monospace";
      context.fillText(`${seconds.toFixed(1)} s`, 265, 215);
      if (seconds < 6) requestAnimationFrame(draw);
      else resolve();
    };
    requestAnimationFrame(draw);
  });
  recorder.stop();
  await stopped;
  const buffer = await new Blob(chunks, { type: mimeType }).arrayBuffer();
  return [...new Uint8Array(buffer)];
});
await fixturePage.close();
await writeFile(fixturePath, Buffer.from(videoBytes));

const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
const browserErrors = [];
const possibleUploads = [];
let watchVideoTraffic = false;
page.on("console", (message) => {
  if (message.type() === "error") browserErrors.push(message.text());
});
page.on("pageerror", (error) => browserErrors.push(error.message));
page.on("request", (request) => {
  if (!watchVideoTraffic || request.url().startsWith("blob:")) return;
  const headers = request.headers();
  const body = request.postData() ?? "";
  if (
    headers["content-type"]?.startsWith("video/") ||
    body.includes("video-locale-fixture") ||
    body.length >= videoBytes.length
  ) {
    possibleUploads.push(`${request.method()} ${request.url()}`);
  }
});

await page.goto(targetUrl, { waitUntil: "networkidle" });
await page.getByLabel("Società").fill("Video QA Club");
await page.getByLabel("Prima categoria").fill("Under 17");
await page.getByLabel("Stagione").fill("2026/27");
await page.getByRole("button", { name: "Crea squadra" }).click();
await page.getByRole("button", { name: "Roster" }).click();
for (let number = 4; number <= 8; number += 1) {
  await page.getByRole("button", { name: "＋ Giocatore" }).click();
  await page.getByLabel("Numero").fill(String(number));
  await page.getByLabel("Nome e cognome").fill(`Video Player ${number}`);
  await page.getByRole("button", { name: "Salva giocatore" }).click();
}
await page.getByRole("button", { name: "Dashboard" }).click();
await page.getByRole("button", { name: /Nuova partita/ }).click();
await page.getByLabel("Avversario", { exact: true }).fill("Video Eagles");
await page.getByRole("button", { name: /Inizia partita/ }).click();
await page.locator(".subject-picker select").selectOption({ label: "#4 Video Player 4" });
await page.getByRole("button", { name: /2✓.*Segnato/ }).click();
const guidedFlow = page.locator(".guided-flow");
if (await guidedFlow.count()) await guidedFlow.getByRole("button", { name: /Salta/ }).click();
await page.getByRole("button", { name: /Report live/ }).click();

await page.getByRole("heading", { name: /Analisi video locale/i }).waitFor();
watchVideoTraffic = true;
await page.locator('input[type="file"][accept="video/*"]').setInputFiles(fixturePath);
await page.locator("video").waitFor();
await page.getByText(/video-locale-fixture\.webm/i).waitFor();
await page.locator("video").evaluate(async (video) => {
  if (video.readyState < 1) {
    await new Promise((resolve) => video.addEventListener("loadedmetadata", resolve, { once: true }));
  }
  if (Number.isFinite(video.duration) && (video.duration < 5 || video.duration > 7)) {
    throw new Error(`Durata metadata inattesa: ${video.duration}`);
  }
});

await page.locator("video").evaluate((video) => { video.currentTime = 0; });
await page.getByRole("button", { name: /Imposta inizio Q1/ }).click();
await page.getByRole("button", { name: /Imposta inizio Q1 ✓/ }).waitFor();
const eventRow = page.locator(".video-event-list article").first();
await eventRow.waitFor();
await eventRow.getByRole("button", { name: /Associa/ }).click();
await eventRow.locator(".video-event-main").click();
await page.getByLabel(/Nota sull’azione/i).fill("Buona spaziatura sul lato debole");
await page.getByLabel(/Nota sull’azione/i).blur();
await page.getByRole("button", { name: "+5s", exact: true }).click();
await page.getByRole("button", { name: "−1s", exact: true }).click();
const currentTime = await page.locator("video").evaluate((video) => video.currentTime);
if (currentTime < 3.5 || currentTime > 4.5) {
  throw new Error(`Seek rapido non corretto: ${currentTime}`);
}

const playerFilter = page.locator(".video-filters").getByLabel("Giocatore");
const playerValue = await playerFilter.locator("option").filter({ hasText: "#4" }).getAttribute("value");
if (!playerValue) throw new Error("Giocatore #4 assente dai filtri video");
await playerFilter.selectOption(playerValue);
await page.locator(".video-filters").getByLabel("Periodo").selectOption("1");
await page.locator(".video-filters").getByLabel("Tipo evento").selectOption("2PT_MADE");
if ((await page.locator(".video-event-list article").count()) !== 1) {
  throw new Error("I filtri video non isolano l'evento atteso");
}
await page.screenshot({ path: `${artifactsDir}/video-desktop.png`, fullPage: true });
if (possibleUploads.length) {
  throw new Error(`Il video locale è stato inviato in rete: ${possibleUploads.join(", ")}`);
}

await page.reload({ waitUntil: "networkidle" });
await page.getByRole("button", { name: "Partite", exact: true }).click();
await page.getByRole("button", { name: /Continua|Apri/, exact: true }).first().click();
if (await page.getByRole("button", { name: /Report live/ }).count()) {
  await page.getByRole("button", { name: /Report live/ }).click();
}
await page.getByRole("heading", { name: /Analisi video locale/i }).waitFor();
await page.getByText(/video-locale-fixture\.webm/i).waitFor();
await page.getByText(/Riseleziona il video locale/i).waitFor();
if (await page.locator("video").count()) {
  throw new Error("Il browser ha conservato impropriamente il file video dopo il reload");
}
await page.locator(".video-event-list article").first().locator(".video-event-main").click();
if (await page.getByLabel(/Nota sull’azione/i).inputValue() !== "Buona spaziatura sul lato debole") {
  throw new Error("La nota video non è stata conservata dopo il reload");
}
await page.locator('input[type="file"][accept="video/*"]').setInputFiles(fixturePath);
await page.locator("video").waitFor();

await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: `${artifactsDir}/video-mobile.png`, fullPage: true });
const overflow = await page.evaluate(
  () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
);
if (overflow) throw new Error("Overflow orizzontale nella sezione video mobile");
if (browserErrors.length) throw new Error(`Errori browser: ${browserErrors.join(" | ")}`);

console.log(
  "QA video locale OK: file, metadata, ancore, evento, note, filtri, seek, privacy, reload e mobile",
);
await context.close();
await browser.close();
